### ISSUE TITLE
[Bug] Crash on server startup

### ISSUE THREAD

**Issue by supersaiyansubtlety** [P3NG00/NetheriteHorseArmorFabric#1]
When trying to load this on my server the server failed to start. 

Here's the [latest.log](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fhastebin.com%252fpiracofehi.rb)

I used the 0.8.9 build 203 fabric launcher, fabric-api-0.14.1+build.372-1.16, and netherite_horse_armor_v0.1.1_1.16.1

I'm running MC on Windows 10. 

This is the output of `java -version` in my `C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64` directory:
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

**Comment by P3NG00** [comment]
Resolved in upcoming version 0.2.0
